SET IDENTITY_INSERT tb_tpp_tipo_processo ON

INSERT INTO tb_tpp_tipo_processo (tpp_id_tipo_processo, tpp_no_nome) VALUES 

-- NCAD
(1,'PROCESSO ADMINISTRATIVO DISCIPLINAR - PAD'),
(2,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(3,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(4,'PROCESSO DE DENÚNCIA DE ILÍCITO'),
(5,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(6,'PROCESSO DE INVESTIGAÇÃO PRELIMINAR'),
(7,'PROCESSO DE REPARAÇÃO DE DANOS - PRD'),
(8,'PROCESSO DE SINDICÂNCIA '),
(9,'PROCESSO DE TOMADA DE CONTAS ESPECIAL'),
(10,'PROCESSO DISCIPLINAR SUMÁRIO - PDS'),
(11,'PROCESSO SANCIONATÓRIO'),

-- NPA
(12,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(13,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(14,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(15,'PROCESSO DE PARCERIAS'),
(16,'PROCESSO DE QUALIFICAÇÃO DE ENTIDADE'),

-- NPE
(17,'PROCESSO DE CÔMPUTO DE TEMPO DE SERVIÇO'),
(18,'PROCESSO DE CONTRIBUIÇÃO SINDICAL'),
(19,'PROCESSO DE DISPONIBILIDADE SINDICAL'),
(20,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO'),
(21,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(22,'PROCESSO DE ENQUADRAMENTO NA CARREIRA'),
(23,'PROCESSO DE FÉRIAS'),
(24,'PROCESSO DE LICENÇAS FUNCIONAIS'),
(25,'PROCESSO DE MOVIMENTAÇÃO FUNCIONAL'),
(26,'PROCESSO DE ORGANIZAÇÃO ADMINISTRATIVA'),
(27,'PROCESSO DE PENSÃO'),
(28,'PROCESSO DE PROGRESSÃO NA CARREIRA'),
(29,'PROCESSO DE PROMOÇÃO'),
(30,'PROCESSO DO SISTEMA DE  ASSISTÊNCIA À SAÚDE'),
(31,'PROCESSO SELETIVO DE RECRUTAMENTO DE PESSOAL'),

-- NPREV
(32,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(33,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(34,'PROCESSO DE ABONO DE PERMANÊNCIA'),
(35,'PROCESSO DE APOSENTADORIA'),
(36,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(37,'PROCESSO DE PENSÃO'),
(38,'PROCESSO DE REFORMA'),
(39,'PROCESSO DE REPARAÇÃO DE DANOS'),
(40,'PROCESSO DE RESERVA REMUNERADA'),

-- NTCE
(41,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS '),
(42,'PROCESSO ADMINISTRATIVO ORIUNDO DO TCE '),
(43,'PROCESSO DE AUDITORIA '),
(44,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO '),
(45,'PROCESSO DE INSPEÇÃO '),
(46,'PROCESSO DE PRESTAÇÃO DE CONTAS '),
(47,'PROCESSO DE REPARAÇÃO DE DANOS - PRD '),
(48,'PROCESSO DE TOMADA DE CONTAS '),

-- NLC
(49,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(50,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(51,'PROCESSO DE ALTERAÇÃO CONTRATUAL'),
(52,'PROCESSO DE BEM DE TERCEIROS'),
(53,'PROCESSO DE CREDENCIAMENTO'),
(54,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(55,'PROCESSO DE LICITAÇÃO'),
(56,'PROCESSO DE USO DE BEM DE TERCEIROS'),

-- NSESAB
(57,'PROCESSO ADMINISTRATIVO ORIUNDO DA SESAB'),
(58,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(59,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(60,'PROCESSO DE ALTERAÇÃO CONTRATUAL'),
(61,'PROCESSO DE BEM DE TERCEIROS'),
(62,'PROCESSO DE CREDENCIAMENTO'),
(63,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(64,'PROCESSO DE LICITAÇÃO'),
(65,'PROCESSO DE PARCERIAS'),
(66,'PROCESSO DE USO DE BEM DE TERCEIROS'),

-- NSAS
(67,'PROCESSO ADMINISTRATIVO ORIUNDO DA SEC'),
(68,'PROCESSO ADMINISTRATIVO ORIUNDO DA SEPROMI'),
(69,'PROCESSO ADMINISTRATIVO ORIUNDO DA SJDHDS'),
(70,'PROCESSO ADMINISTRATIVO ORIUNDO DA SPM'),
(71,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(72,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(73,'PROCESSO DE ALTERAÇÃO CONTRATUAL'),
(74,'PROCESSO DE BEM DE TERCEIROS'),
(75,'PROCESSO DE CREDENCIAMENTO'),
(76,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(77,'PROCESSO DE LICITAÇÃO'),
(78,'PROCESSO DE PARCERIAS'),
(79,'PROCESSO DE USO DE BEM DE TERCEIROS'),

-- NSSP
(80,'PROCESSO ADMINISTRATIVO ORIUNDO DA SSP'),
(81,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(82,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(83,'PROCESSO DE ALTERAÇÃO CONTRATUAL'),
(84,'PROCESSO DE BEM DE TERCEIROS'),
(85,'PROCESSO DE CREDENCIAMENTO'),
(86,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(87,'PROCESSO DE LICITAÇÃO'),
(88,'PROCESSO DE PARCERIAS'),
(89,'PROCESSO DE QUALIFICAÇÃO DE ENTIDADE'),
(90,'PROCESSO DE USO DE BEM DE TERCEIROS'),

-- NPMA
(91,'PROCESSO ADMINISTRATIVO ORIUNDO DE OUTROS ÓRGÃOS'),
(92,'PROCESSO ADMINISTRATIVO ORIUNDO DO MP'),
(93,'PROCESSO DE BEM DE TERCEIROS'),
(94,'PROCESSO DE BEM PÚBLICO'),
(95,'PROCESSO DE ELABORAÇÃO/REVISÃO DE ATO NORMATIVO/DOCUMENTO'),
(96,'PROCESSO DE REGULARIÇÃO FUNDIÁRIA'),
(97,'PROCESSO DE REGULARIÇÃO TERRITORIAL'),
(98,'PROCESSO DE REGULARIZAÇÃO FUNDIÁRIA'),
(99,'PROCESSO DE REPARAÇÃO DE DANOS - PRD'),
(100,'PROCESSO DE USO DE BEM DE TERCEIROS'),
(101,'PROCESSO DE USO DE BEM PÚBLICO'),
(102,'PROCESSO SOBRE MEIO AMBIENTE'),
(103,'PROCESSO SOBRE ORÇAMENTO PÚBLICO')

SET IDENTITY_INSERT tb_tpp_tipo_processo OFF