SET IDENTITY_INSERT tb_orgao ON

INSERT INTO tb_orgao (id, nome, descricao) VALUES 

(1,'ADAB ','Agência Estadual de Defesa Agropecuária da Bahia'),
(2,'AGERBA ','Agência Estadual de Regulação de Serviços Públicos de Energia, Transportes e Comunicações da Bahia'),
(3,'AGERSA ','Agência Reguladora de Saneamento Básico do Estado da Bahia'),
(4,'BAHIAFARMA ','Fund. Baiana de Pesquisa Científica, Desenv. Tecnológico, Fornecimento e Distribuição de Medicamentos'),
(5,'BAHIAGÁS ','Companhia de Gás da Bahia'),
(6,'BAHIAPESCA ','Bahia Pesca S.A.'),
(7,'BAHIATURSA ','Superintendência de Fomento ao Turismo do Estado da Bahia'),
(8,'CAR ','Companhia de Desenvolvimento e Ação Regional'),
(9,'CBMBA ','Corpo de Bombeiros Militar da Bahia'),
(10,'CBPM ','Companhia Baiana de Pesquisa Mineral'),
(11,'CCIVIL ','Casa Civil'),
(12,'CERB ','Companhia de Engenharia Hídrica e de Saneamento da Bahia'),
(13,'CIS ','Centro Industrial de Subaé'),
(14,'CONDER ','Companhia de Desenvolvimento Urbano do Estado da Bahia'),
(15,'CTB ','Companhia de Transportes do Estado da Bahia'),
(16,'DESENBAHIA ','Agência de Fomento do Estado da Bahia S.A.'),
(17,'DETRAN ','Departamento Estadual de Trânsito'),
(18,'EMBASA ','Empresa Baiana de Águas e Saneamento S.A.'),
(19,'FAPESB ','Fundação de Amparo à Pesquisa do Estado da Bahia'),
(20,'FPC ','Fundação Pedro Calmon'),
(21,'FUNCEB ','Fundação Cultural do Estado da Bahia'),
(22,'FUNDAC ','Fundação da Criança e do Adolescente'),
(23,'HEMOBA ','Fundação de Hematologia e Hemoterapia da Bahia'),
(24,'IBAMETRO ','Instituto Baiano de Metrologia e Qualidade'),
(25,'INEMA ','Instituto do Meio Ambiente e Recursos Hídricos'),
(26,'IPAC ','Instituto do Patrimônio Artístico e Cultural da Bahia'),
(27,'IRDEB ','Instituto de Radiodifusão Educativa da Bahia'),
(28,'JUCEB ','Junta Comercial do Estado da Bahia'),
(29,'MPE','Ministério Público do Estado'),
(30,'PCBA ','Polícia Civil do Estado da Bahia'),
(31,'PGE','Procuradoria Geral do Estado'),
(32,'PMBA ','Polícia Militar da Bahia'),
(33,'PRODEB ','Companhia de Processamento de Dados do Estado da Bahia'),
(34,'SAEB ','Secretaria da Administração'),
(35,'SDE ','Secretaria de Desenvolvimento Econômico'),
(36,'SDR ','Secretaria de Desenvolvimento Rural'),
(37,'SEAGRI ','Secretaria da Agricultura, Pecuária, Irrigação, Pesca e Aquicultura'),
(38,'SEAP ','Secretaria de Administração Penitenciária e Ressocialização'),
(39,'SEC ','Secretaria da Educação'),
(40,'SECOM ','Secretaria de Comunicação Social'),
(41,'SECTI ','Secretaria de Ciência, Tecnologia e Inovação'),
(42,'SECULT','Secretaria de Cultura'),
(43,'SEDUR ','Secretaria de Desenvolvimento Urbano'),
(44,'SEFAZ ','Secretaria da Fazenda'),
(45,'SEI ','Superintendência de Estudos Econômicos e Sociais da Bahia'),
(46,'SEINFRA ','Secretaria de Infraestrutura'),
(47,'SEMA ','Secretaria do Meio Ambiente'),
(48,'SEPLAN ','Secretaria do Planejamento'),
(49,'SEPROMI ','Secretaria de Promoção da Igualdade Racial'),
(50,'SERIN ','Secretaria de Relações Institucionais'),
(51,'SESAB ','Secretaria da Saúde'),
(52,'SETRE ','Secretaria do Trabalho, Emprego, Renda e Esporte'),
(53,'SETUR ','Secretaria de Turismo'),
(54,'SIHS ','Secretaria de Infraestrutura Hídrica e Saneamento'),
(55,'SJDHDS ','Secretaria de Justiça, Direitos Humanos e Desenvolvimento Social'),
(56,'SPM ','Secretaria de Políticas para As Mulheres'),
(57,'SSP ','Secretaria da Segurança Pública'),
(58,'SUDESB ','Superintendência Dos Desportos do Estado da Bahia'),
(59,'SUDIC ','Superintendência de Desenvolvimento Industrial e Comercial'),
(60,'TCE ','Tribunal de Contas do Estado'),
(61,'UEFS ','Universidade Estadual de Feira de Santana'),
(62,'UESB ','Universidade Estadual do Sudoeste da Bahia'),
(63,'UESC ','Universidade Estadual de Santa Cruz'),
(64,'UNEB ','Universidade do Estado da Bahia')

SET IDENTITY_INSERT tb_orgao OFF